Feat/issue 52/Log out user
chingu-voyages/v44-tier3-team-42 pull request #62
Opened 2023-06-06 13:18 UTC by Remi-dee

# This PR resolves #52

2023-06-06 17:15 UTC, TazDeCoder requested changes
Hello @Remi-dee, I've noticed that some files have deletions that are really important to keep, I suggest you kindly "undo" your deletions for the appropriate marked files. Other than that everything else looks good.

2023-06-06 17:15 UTC, TazDeCoder commented on next.config.js
Can you please undo the deletion of lines 10 - 17

2023-06-07 08:31 UTC, Remi-dee commented
> Hello @Remi-dee, I've noticed that some files have deletions that are really important to keep, I suggest you kindly "undo" your deletions for the appropriate marked files. Other than that everything else looks good.

Hi @TazDeCoder, Thanks for your overseeing, not exactly sure while those changes where made but i guess it's somewhere around when i was fixing a merge conflict with dev branch.
I've fixed them now, so you can review.

2023-06-07 09:51 UTC, TazDeCoder approved these changes

2023-06-08 20:47 UTC, merged